# Generated by Django 5.1.2 on 2024-10-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catedraticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carnet', models.CharField(max_length=20, unique=True)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('CUI', models.CharField(max_length=13, unique=True)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=10)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Profesion', models.CharField(max_length=50)),
                ('No_Colegiado', models.CharField(max_length=10)),
            ],
        ),
    ]
