# Generated by Django 5.1.2 on 2024-10-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catedraticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catedraticos',
            name='No_Colegiado',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
