# Generated by Django 5.1.2 on 2024-10-23 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carrera', '0001_initial'),
        ('Cursos', '0001_initial'),
        ('Facultad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semestre', models.CharField(max_length=50)),
                ('Id_Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrera.carrera')),
                ('Id_Cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.cursos')),
                ('Id_Facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facultad.facultad')),
            ],
        ),
    ]
