# Generated by Django 5.1.2 on 2024-10-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Carrera', models.CharField(max_length=20, unique=True)),
                ('Nombre_Carrera', models.CharField(max_length=75)),
            ],
        ),
    ]
